# Build stage
FROM python:3.12.1-slim as build

WORKDIR /

COPY requirements.txt ./
RUN pip3 install -vvv --require-hashes --no-cache-dir -r requirements.txt

COPY test-requirements.txt ./
RUN pip3 install --no-cache-dir --require-hashes -r test-requirements.txt

COPY productpage.py /opt/microservices/
COPY templates /opt/microservices/templates
COPY static /opt/microservices/static
COPY requirements.txt /opt/microservices/

# Test stage
FROM build as test

COPY tests/unit /opt/microservices/tests/unit
WORKDIR /opt/microservices
RUN python -m unittest discover

# Run stage
FROM python:3.12.1-slim

WORKDIR /opt/microservices

COPY --from=build /opt/microservices /opt/microservices

ARG flood_factor
ENV FLOOD_FACTOR=${flood_factor:-0}
EXPOSE 9080

CMD ["gunicorn", "-b", "[::]:9080", "productpage:app", "-w", "8", "--keep-alive", "2", "-k", "gevent"]

USER 1000
